version: '3.8'

services:
  opsbot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./systems.json:/app/systems.json:ro
    restart: unless-stopped